### PR TITLE
Added function to receive events :)

### PR DESCRIPTION
**Pull request by Splinti**
Hope youll like it, I just modified the code a little bit. I missed this
feature so I added it by myself

### CODE REVIEW

**Comment by matthin** [comment]
Thanks for the pull request. Once I get some free time either today or tomorrow I'll test it out.

However from looking at the code I don't see how it could actually work with server query events. Could you explain a little bit about how this works from a end-users perspective? Maybe show a quick code example to help me out once I get time to test this?

**Comment by Splinti** [comment]
Sure why not
http://pastebin.com/eVpQLDAi
There is some code which puts you the messages somebody wrote in the root channel (Server channel) and tells you something like this: 
Screenshot
After that you can easily write a methods which response as an textmessage to the user when he write !help or something like that :)

**Comment by matthin** [comment]
Shouldn't this work just using the command method like:
 `@ts.command("servernotifyregister", {"event": "textserver"}) `?

**Comment by Splinti** [comment]
No, the method command will wait for one response, then quit / skipping to the next step

**Comment by matthin** [comment]
Thanks, I'll accept the pull request and then fix up the code a little bit.

I'm putting together some ideas of how to enable events to be received in the background, so a user can subscribe to an event and get a callback-like response every time the client receives a notification. Since I'm pretty sure that's how it's supposed to work. If that functionally even makes sense and you're interested, I can send you a message once I have a prototype. It might not be possible with MRI due to the GIL though.

**Comment by matthin** [comment]
I've [merged](https://github.com/matthin/teamspeak-ruby/commit/b10bf145a37ff1d604546cbf43a21f4f111778dc) the event notification implementation into the command method. If you like the implementation I'll push an update to RubyGems.

Thanks again for bringing this to my attention.

**Comment by Splinti** [comment]
No problem. You don't even know how happy I am that I've helped at least by the idea :D
This iy my first contribution outside of my friends-area so yeah Im happy to help you :D

**Comment by matthin** [comment]
I'm glad that you're happy :)

I've pushed 1.0.5 to RubyGems, so now the whole community has access to event notification functionality thanks to you.

**Pull request merged**
